### ISSUE TITLE
Release 0.0.2 版本内打包的插件版本信息仍为 0.0.1

### ISSUE THREAD

**Issue by erha19** [opensumi/shortcuts-guard#18]
![image](https://user-images.githubusercontent.com/9823838/182287021-96b6d0d1-773f-4ac8-8bfd-44b3c245ebdc.png)

**Comment by erha19** [comment]
同时，这个版本提供的 glob 表达式模式，整体功能上不可用了

**Comment by erha19** [comment]
https://user-images.githubusercontent.com/9823838/182288831-d1836e1a-f4d3-47b6-a283-f7832a960f52.mp4

以 `CMD+N` 为例，偶尔生效偶尔不生效

**Comment by bytemain** [comment]
https://github.com/opensumi/shortcuts-guard/blob/main/src/scripts/background.ts#L11

我猜是这里的原因导致的，这里是一个异步获取当前配置的 urls 方法，就会存在你按键时这里还没获取到值的情况。

可能也不是这个原因。

**Comment by hipedon** [comment]
@erha19 这里显示为0.0.1，是因为 [manifest.json](https://github.com/opensumi/shortcuts-guard/blob/main/src/manifest.json#L4) 没有及时更新。
